### ISSUE TITLE
forge pls?

### ISSUE THREAD

**Issue by Vadewolf** [MrLoLf/InfinityAndMending#1]
can this mod be for forgs also pretty pls? asking cause it used to be for forge but now only shows up for fabric and this mod on forge is so helpful pls and ty

**Comment by MrLoLf** [comment]
There was never a forge version of this mod, and there never will be one. I've developed this only for Fabric, and I will only develop this for Fabric. This mod is licensed under MIT, so every one could do a Forge port for it, including yourself. You can do an PR for it or even create your own Project.
